# Generated by Django 5.1.3 on 2024-11-21 10:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='products_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='products_images'),
        ),
    ]
